name: Docker C

on:
    push:
        branches:
            - main

jobs:
    test-and-buid:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Verify HTML Exists
              run: ls -l index.html
            - name: Build Docker Image
              run: docker build -t cicd-demo .
            - name: Run Container
              run: docker run -d -p 8080:80 --name test-container cicd-demo
            - name: Test Website
              run: |
                sleep 5
                curl -f http://localhost:8080 || exit 1
            - name: Stop Container
              run: docker stop test-container    